title: Deploy
summary: This handler will upload all of the step assets to S3, also slim-spec, spec, and spec.gz JSONs.
description: This handler will upload all of the step assets to S3, also slim-spec, spec, and spec.gz JSONs.

website: https://github.com/bitrise-io/bitrise-steplib
source_code_url: https://github.com/bitrise-io/bitrise-steplib
support_url: https://github.com/bitrise-io/bitrise-steplib/issues

toolkit:
  go:
    package_name: github.com/bitrise-io/bitrise-steplib/handlers/deploy

deps:
  brew:
  - name: awscli

inputs: 
- steps_dir: ./steps
  opts:
    is_required: true
- collection_uri: file://./
  opts:
    is_required: true
- spec_json_path: $SPEC_JSON
  opts:
    is_required: true
- slim_spec_json_path: $SLIM_SPEC_JSON
  opts:
    is_required: true
