title: Step Info
summary: This handler collects changed files, if there was a step change then it exports the stepid@version composite.
description: This handler collects changed files, if there was a step change then it exports the stepid@version composite.

website: https://github.com/bitrise-io/bitrise-steplib
source_code_url: https://github.com/bitrise-io/bitrise-steplib
support_url: https://github.com/bitrise-io/bitrise-steplib/issues

toolkit:
  go:
    package_name: github.com/bitrise-io/bitrise-steplib/handlers/step-info

is_skippable: true

outputs:
- STEP_INFO_ID:
- STEP_INFO_VERSION:
- STEP_INFO_COMPOSITE: